language: objective-c
osx_image: xcode7.3
xcode_workspace: EverliveSdkTests.xcworkspace
xcode_scheme: EverliveSdkTestsTests
xcode_sdk: iphonesimulator9.3
before_install:
 - brew update
 - brew install tailor
<<<<<<< HEAD
 - cd Tests

script: set -o pipefail && xcodebuild test -workspace EverliveSdkTests.xcworkspace -scheme EverliveSdkTestsTests -sdk iphonesimulator9.3
=======

script: set -o pipefail && xcodebuild test -workspace Tests/EverliveSdkTests.xcworkspace -scheme EverliveSdkTestsTests -sdk iphonesimulator9.3
>>>>>>> d6f126ad8a6082cf55fb8bb323e8c4b15285df80
